version: '3.7'

services:

  postgres:
    container_name: postgres-cf-redis
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  cf-redis-service-1:
    container_name: cf-redis-service-1
    image: ere/cf-redis-service
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: stg
    ports:
      - "8080:8080"

  cf-redis-service-2:
    container_name: cf-redis-service-2
    image: ere/cf-redis-service
    environment:
      SERVER_PORT: 8081
      SPRING_PROFILES_ACTIVE: stg
    ports:
      - "8081:8081"

  redis:
    image: 'bitnami/redis:latest'
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379

volumes:
  postgres_data:
